---
title: "Can we use SOC in the top 15cm as a proxy for SOC to 100cm deep?"
author: "CK, PR, KBD, RE & SE"
date: "25 July 2018"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_knit$set(echo = TRUE, root.dir = "C:/Users/eschenr/Dropbox/WW_SESYNC/data/Soil_data_Baringo/")
# With the code we set up the environment: load required packages and define where the data and outputs are located

rm(list=ls(all=TRUE))

require(nlme)
require(lme4)
require(openxlsx)
require(lmerTest)
require(ggplot2)
require(knitr)
library(reshape)
library(reshape2)
require(plyr)
require(dplyr)

```

```{r load_data, echo=FALSE}
data=read.xlsx("SOC_ALL_results_276_Final_252 RE.xlsx", sheet=1)
data$count<-1
# plot(data[,c(3:8)])
```

We loaded the data to compare SOC in the top 15 cm and the top 100cm.

```{r Puritys_subset, echo=FALSE}
Purity=subset(data,Dataset=="Purity")
Purity2=subset(Purity,Depth==15)
plot(Purity2[,c(3:5,8,10)])

plot(TotalC015~Depth,data=Purity,pch=as.numeric(as.factor(Purity$Landcover)),bty="l",las=1,col=as.numeric(as.factor(Purity$Landcover)))

# 1 = degraded
# 2 = pristine
# 3 = prosopis_high
# 4 = prosopis_low
# 5 = restored
```

We only focus on Purity's data for the moment: is there a relationship between SOC in the top 15cm and total SOC?

```{r plot_data, echo=FALSE}
plot(Total~TotalC015,data=Purity,pch=16,bty="l",las=1,col=as.numeric(as.factor(Purity$Landcover)),cex=as.numeric(as.factor(Purity$Landcover)))
```

It appears that for some landcover types, there is no relationship between SOC in the top layer and the total SOC content. 

```{r analyse_data, echo=FALSE}
model=Purity2$Total~Purity2$TotalC015*Purity2$Landcover
summary(aov(lm(model)))
head(Purity2)
```
There are significant differences
```{r analyse_data, echo=FALSE}
plot(lm(model)$resid)
```
